### ISSUE TITLE
AI Tool: handle error for short texts

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-ui#203]
On a short description the AI endpoint returns an error that we don't properly handle yet.

**Comment by timber-they** [comment]
Example:
```bash
$ curl --request POST  --url 'http://49.12.65.167:3001/recommendations/chats?api_key=a61d2acd-de1b-48d5-a3a2-9f41c8f0b47e'  --header 'Content-Type: application/json'  --data '{
        "text_to_analyze" : "some test text"
}' --verbose
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 49.12.65.167:3001...
* Connected to 49.12.65.167 (49.12.65.167) port 3001 (#0)
> POST /recommendations/chats?api_key=a61d2acd-de1b-48d5-a3a2-9f41c8f0b47e HTTP/1.1
> Host: 49.12.65.167:3001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 41
> 
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 923
< Date: Tue, 16 Apr 2024 09:13:05 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Text to analyze is to short<br> &nbsp; &nbsp;at file:///app/index_vector.js:66:15<br> &nbsp; &nbsp;at newFn (/app/node_modules/express-async-errors/index.js:16:20)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/route.js:144:13)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:137:5<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:206:9)<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/app/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:518:28)</pre>
</body>
</html>
* Connection #0 to host 49.12.65.167 left intact
```

It's curious that this is an error 500 (internal server error) though, which is also not documented. I'm gonna implement a handler for this, but it seams as if there might be some adjustment needed on the side of the AI tool.

**Comment by timber-they** [comment]
There also seem to be additional undocumented errors, e.g.:
```bash
$ curl --request POST  --url 'http://49.12.65.167:3001/recommendations/chats?api_key=a61d2acd-de1b-48d5-a3a2-9f41c8f0b47e'  --header 'Content-Type: application/json'  --data '{
        "text_to_analyze" : "............................................................................................................."
}' --verbose
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 49.12.65.167:3001...
* Connected to 49.12.65.167 (49.12.65.167) port 3001 (#0)
> POST /recommendations/chats?api_key=a61d2acd-de1b-48d5-a3a2-9f41c8f0b47e HTTP/1.1
> Host: 49.12.65.167:3001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 136
> 
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 922
< Date: Tue, 16 Apr 2024 09:18:09 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Query has unknown language<br> &nbsp; &nbsp;at file:///app/index_vector.js:86:15<br> &nbsp; &nbsp;at newFn (/app/node_modules/express-async-errors/index.js:16:20)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/route.js:144:13)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:137:5<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:206:9)<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/app/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:518:28)</pre>
</body>
</html>
* Connection #0 to host 49.12.65.167 left intact
```

I'm just gonna treat 500 errors as 400 errors and print the error message as message in the frontend (like *Query has unknown language* or *Text to analyze is too short*), but better defined error messages would certainly be helpful, also to avoid English messages in a German application.
