### ISSUE TITLE
badge award via qr code fails

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#645]
```
Internal Server Error: /v1/issuer/issuers/G9WvM2esQyupkoXzoY-6FQ/badges/o9N4EEFKSz-kMJMHStWtvg/assertions
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/apispec_drf/decorators.py", line 154, in wrapper
api-1  |     return wrapped(*args, **kwargs)
api-1  |   File "/badgr_server/apps/issuer/api.py", line 468, in post
api-1  |     return super(BadgeInstanceList, self).post(request, **kwargs)
api-1  |   File "/badgr_server/apps/entity/api.py", line 87, in post
api-1  |     new_instance = serializer.save(created_by=request.user)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
api-1  |     self.instance = self.create(validated_data)
api-1  |   File "/badgr_server/apps/issuer/serializers_v1.py", line 538, in create
api-1  |     return self.context.get('badgeclass').issue(
api-1  |   File "/badgr_server/apps/issuer/models.py", line 879, in issue
api-1  |     return BadgeInstance.objects.create(
api-1  |   File "/badgr_server/apps/issuer/managers.py", line 349, in create
api-1  |     new_instance.notify_earner(badgr_app=badgr_app)
api-1  |   File "/badgr_server/apps/issuer/models.py", line 1316, in notify_earner
api-1  |     adapter.send_mail(template_name, self.recipient_identifier, context=email_context)
api-1  |   File "/badgr_server/apps/mainsite/account_adapter.py", line 195, in send_mail
api-1  |     with open(img_path, 'rb') as f:
api-1  | FileNotFoundError: [Errno 2] No such file or directory: '/badgr_server/mediafiles/uploads/badges/assertion-1htQgnQ4TMS9HMeIJrYlrQ.png'
```

**Comment by jona159** [comment]
The problem seems to be that we can still upload ```.jpg``` files for the badge image, althogh we say that we only support png and svg.

**Comment by timber-they** [comment]
@jona159 While this certainly makes sense and on the long-term solves the issue, we should probably still add something to mitigate the PDF export error
