### ISSUE TITLE
end-to-end tests: automate execution

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#787]

**Comment by timber-they** [comment]
To add some description here, we want to automatically run the E2E-tests (from [OEB-test](https://github.com/mint-o-badges/oeb-test)) for UI-PRs.

**Comment by timber-they** [comment]
TODOs:
- [ ] Fix current E2E-tests
- [ ] Make tests executable in local `docker`
- [x] Create a workflow that waits for the netlify preview
- [ ] Run tests for a PR

**Comment by timber-they** [comment]
I'm a bit stuck and posted a question on [SO](https://stackoverflow.com/questions/79215210/selenium-chrome-standalone-download-file-without-popup) about making the downloads in Selenium work within the docker container. Other than that, the point *Make tests executable in local `docker`* is done. The last TODO shouldn't be too much work anymore then (though it might be difficult to test).

**Comment by zven** [comment]
@timber-they Any insights from the stackoverflow post yet?

**Comment by timber-they** [comment]
Some. There's one more thing I can try (setting the path explicitly). If that's not successful, I'll try installing the "normal" chrome instead of the selenium provided one. If this also doesn't work, I'm confused.

**Comment by timber-they** [comment]
The download problem seems to be solved. It was a permission on problem, since the download directory that I synced from the other container was owned by `root`. I now switched to using `/tmp` (synced across the `node` and `chrome` containers), which seems to work. Now only the last two points (automatically adjusting the config for PRs and running the tests for PRs) remain. @zven fyi

**Comment by timber-they** [comment]
For some reason the execution on github doesn't quite work yet:
```js
> test
> npx mocha test
  Badge Test
    1) "before all" hook for "should login"
    2) "after all" hook for "delete the competency badge"
  Issuer Test
    3) "before all" hook for "should create an issuer"
    4) "after all" hook for "should verify the issuer details"
  Login Test
    5) "before all" hook for "should be able to log in"
    6) "after all" hook for "should be able to log in"
  QR test
    7) "before all" hook for "should create a badge"
    8) "after all" hook for "should receive the badge"
  Signup Test
    9) "before all" hook for "should be able to sign up"
Deleting the user failed. Response: Response {
  status: 401,
  statusText: 'Unauthorized',
  headers: Headers {
    'access-control-allow-origin': '*',
    allow: 'GET, POST, PUT, DELETE, HEAD, OPTIONS',
    'content-length': '38',
    'content-type': 'application/json',
    date: 'Thu, 16 Jan 2025 14:29:21 GMT',
    server: 'nginx/1.26.2',
    vary: 'Accept, Authorization, Cookie, Origin,Origin',
    'www-authenticate': '***"api"',
    'x-frame-options': 'DENY'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: false,
  redirected: false,
  type: 'basic',
  url: 'https://api.staging.openbadges.education/v1/user/profile'
}
    10) "after all" hook for "should verify user details"
  Title Test
    11) "before all" hook for "should match the expected title"
    12) "after all" hook for "should match the expected title"
  0 passing (8s)
  12 failing
  1) Badge Test
       "before all" hook for "should login":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  2) Badge Test
       "after all" hook for "delete the competency badge":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/badge.spec.js:118:22)
      at process.processImmediate (node:internal/timers:511:21)
  3) Issuer Test
       "before all" hook for "should create an issuer":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  4) Issuer Test
       "after all" hook for "should verify the issuer details":
     AssertionError [ERR_ASSERTION]: Failed to find the issuer
      at deleteIssuerOverApi (file:///__w/badgr-ui/badgr-ui/test/issuer.js:101:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/issuer.spec.js:41:9)
  5) Login Test
       "before all" hook for "should be able to log in":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  6) Login Test
       "after all" hook for "should be able to log in":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/login.spec.js:23:36)
      at process.processImmediate (node:internal/timers:511:21)
  7) QR test
       "before all" hook for "should create a badge":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  8) QR test
       "after all" hook for "should receive the badge":
     AssertionError [ERR_ASSERTION]: Failed to find the badge
      at deleteBadgeOverApi (file:///__w/badgr-ui/badgr-ui/test/badge.js:350:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/qr.spec.js:78:9)
  9) Signup Test
       "before all" hook for "should be able to sign up":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  10) Signup Test
       "after all" hook for "should verify user details":
      AssertionError [ERR_ASSERTION]: The user deletion failed, probably because the HTTP response code wasn't 2xx
      + expected - actual
      -false
      +true
      
      at deleteUserOverApi (file:///__w/badgr-ui/badgr-ui/test/signup.js:68:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/signup.spec.js:35:9)
  11) Title Test
       "before all" hook for "should match the expected title":
     Error: Server terminated early with status 127
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  12) Title Test
       "after all" hook for "should match the expected title":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/title.spec.js:26:36)
      at process.processImmediate (node:internal/timers:511:21)
Error: Process completed with exit code 12.
```

**Comment by zven** [comment]
@timber-they If no changes are needed in the `oeb-test` repo, please already create a PR for the adjustments you made. 👍

**Comment by timber-they** [comment]
I've created a [PR](https://github.com/mint-o-badges/oeb-test/pull/5) for `oeb-test`. Also, I managed to change the error message ^^ I'm gonna look into it further the next few days:
```js
  0 passing (4m)
  23 failing
  1) Badge Test
       should login:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"input[placeholder="Dein Passwort"]"}
  (Session info: chrome=131.0.6778.204)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:744:17)
      at async login (file:///__w/badgr-ui/badgr-ui/test/login.js:17:27)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/badge.spec.js:55:9)
  2) Badge Test
       should create a participation badge:
     TimeoutError: Couldn't find card
Wait timed out after 13328ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  3) Badge Test
       should validate the participation badge:
     TimeoutError: Couldn't find card
Wait timed out after 13361ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  4) Badge Test
       delete the participation badge:
     AssertionError [ERR_ASSERTION]: Failed to find the badge
      at deleteBadgeOverApi (file:///__w/badgr-ui/badgr-ui/test/badge.js:350:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/badge.spec.js:71:9)
  5) Badge Test
       should create a competency badge:
     TimeoutError: Couldn't find card
Wait timed out after 13300ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  6) Badge Test
       should validate the competency badge:
     TimeoutError: Couldn't find card
Wait timed out after 13270ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  7) Badge Test
       should award the competency badge:
     TimeoutError: Couldn't find card
Wait timed out after 13272ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  8) Badge Test
       should receive the competency badge:
     TimeoutError: Waiting for element to be located By(link text, automated test title)
Wait timed out after 13323ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  9) Badge Test
       should download the pdf from the backpack:
     TimeoutError: Waiting for element to be located By(link text, automated test title)
Wait timed out after 13306ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  10) Badge Test
       should download the pdf from the internal issuer page:
     TimeoutError: Couldn't find card
Wait timed out after 13279ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  11) Badge Test
       should revoke the competency badge:
     TimeoutError: Couldn't find card
Wait timed out after 13318ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  12) Badge Test
       delete the competency badge:
     AssertionError [ERR_ASSERTION]: Failed to find the badge
      at deleteBadgeOverApi (file:///__w/badgr-ui/badgr-ui/test/badge.js:350:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/badge.spec.js:114:9)
  13) Issuer Test
       should create an issuer:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"input[placeholder="Dein Passwort"]"}
  (Session info: chrome=131.0.6778.204)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:744:17)
      at async login (file:///__w/badgr-ui/badgr-ui/test/login.js:17:27)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/issuer.spec.js:29:9)
  14) Issuer Test
       should verify the issuer details:
     TimeoutError: Waiting for element to be located By(link text, automatedTestName)
Wait timed out after 13263ms
      at /__w/badgr-ui/badgr-ui/node_modules/selenium-webdriver/lib/webdriver.js:915:22
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  15) Issuer Test
       "after all" hook for "should verify the issuer details":
     AssertionError [ERR_ASSERTION]: Failed to find the issuer
      at deleteIssuerOverApi (file:///__w/badgr-ui/badgr-ui/test/issuer.js:101:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/issuer.spec.js:41:9)
  16) Login Test
       "before all" hook for "should be able to log in":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/badgr-ui/badgr-ui/test/login.spec.js)
      at listOnTimeout (node:internal/timers:614:17)
      at process.processTimers (node:internal/timers:549:7)
  17) Login Test
       "after all" hook for "should be able to log in":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/login.spec.js:23:36)
      at process.processImmediate (node:internal/timers:511:21)
  18) QR test
       "before all" hook for "should create a badge":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/badgr-ui/badgr-ui/test/qr.spec.js)
      at listOnTimeout (node:internal/timers:614:17)
      at process.processTimers (node:internal/timers:549:7)
  19) QR test
       "after all" hook for "should receive the badge":
     AssertionError [ERR_ASSERTION]: Failed to find the badge
      at deleteBadgeOverApi (file:///__w/badgr-ui/badgr-ui/test/badge.js:350:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/qr.spec.js:78:9)
  20) Signup Test
       "before all" hook for "should be able to sign up":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/badgr-ui/badgr-ui/test/signup.spec.js)
      at listOnTimeout (node:internal/timers:614:17)
      at process.processTimers (node:internal/timers:549:7)
  21) Signup Test
       "after all" hook for "should verify user details":
      AssertionError [ERR_ASSERTION]: The user deletion failed, probably because the HTTP response code wasn't 2xx
      + expected - actual
      -false
      +true
      
      at deleteUserOverApi (file:///__w/badgr-ui/badgr-ui/test/signup.js:68:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/signup.spec.js:35:9)
  22) Title Test
       "before all" hook for "should match the expected title":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/badgr-ui/badgr-ui/test/title.spec.js)
      at listOnTimeout (node:internal/timers:614:17)
      at process.processTimers (node:internal/timers:549:7)
  23) Title Test
       "after all" hook for "should match the expected title":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (file:///__w/badgr-ui/badgr-ui/test/title.spec.js:26:36)
      at process.processImmediate (node:internal/timers:511:21)
Error: Process completed with exit code 23.
```

**Comment by zven** [comment]
I was already wondering what it's about with this issue. ;-) Since the automated execution is implemented, we can close this issue. 👍
